Repository msktutil/msktutil, pull requests merged in 2021-09, with the labels that each got.

#108 Delete and reset computer account
  ldapconnection.cpp
  ldapconnection.h
  msktldap.cpp
  msktutil.cpp
  msktutil.h
Labels: enhancement

#186 Clean up --remove-enctype option parsing
  msktutil.cpp
Labels: bug

#185 Enable CodeQL scanning
  .github/workflows/codeql-analysis.yml
Labels: enhancement, security
